name: Daily Twitter Alerts

on:
  schedule:
    - cron: '30 0 * * *'  # 6:00 AM IST
  workflow_dispatch:

jobs:
  x-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install snscrape requests

      - name: Run Twitter scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python twitter_scraper.py
