name: Daily Web Mentions Digest

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6:00 AM UTC (11:30 AM IST)
  workflow_dispatch:

jobs:
  run-web-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run web mentions digest script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python web_mentions_digest_with_summaries.py
